# Generated by Django 5.0 on 2023-12-08 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('food_description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude_longitude_geo', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
